site_name: Craftspot Svelte
site_url: https://example.com
repo_url: https://github.com/Fiona-Waters/testRepo/tree/develop/placemark-svelte
theme: readthedocs
plugins:
  - search
docs_dir: docs
pages:
- 'index.md'
- 'about.md'
- moreDocs/insidefolder.md
